[[areas]]
name = "RLS"
directories = []
crates = []
experts = ["matklad", "xanewok"]
familiar = []

[[areas]]
name = "query system"
directories = ["compiler/rustc_query_impl", "compiler/rustc_query_system"]
crates = []
experts = ["eddyb", "michaelwoerister", "nikomatsakis"]
familiar = []

[[areas]]
name = "metadata encoding/decoding"
directories = ["compiler/rustc_metadata"]
crates = []
experts = ["michaelwoerister", "oli-obk"]
familiar = []

[[areas]]
name = "incremental compilation"
directories = []
crates = []
experts = ["michaelwoerister", "nikomatsakis"]
familiar = ["wesleywiser"]

[[areas]]
name = "codegen unit partitioning"
directories = ["compiler/rustc_mir/src/monomorphize/partitioning"]
crates = []
experts = ["michaelwoerister", "wesleywiser"]
familiar = []

[[areas]]
name = "ThinLTO"
directories = []
crates = []
experts = ["alexcrichton", "michaelwoerister"]
familiar = []

[[areas]]
name = "linker-plugin LTO (xLTO)"
directories = []
crates = []
experts = ["michaelwoerister"]
familiar = []

[[areas]]
name = "Typeck"
directories = ["compiler/rustc_typeck"]
crates = []
experts = ["eddyb", "nikomatsakis"]
familiar = []

[[areas]]
name = "miri"
directories = [
    "compiler/rustc_middle/mir/interpret",
    "compiler/rustc_mir/interpret",
]
crates = []
experts = ["eddyb", "oli-obk", "RalfJung"]
familiar = []

[[areas]]
name = "Diagnostics"
directories = []
crates = []
experts = ["estebank", "oli-obk", "zackmdavis"]
familiar = ["davidtwco", "spastorino"]

[[areas]]
name = "Parser"
directories = [
    "compiler/rustc_ast/ast.rs",
    "compiler/rustc_ast/util",
    "compiler/rustc_parse",
]
crates = []
experts = ["petrochenkov", "estebank"]
familiar = ["davidtwco"]

[[areas]]
name = "Lexer"
directories = [
    "compiler/rustc_lexer",
    "compiler/rustc_parse/parse/lexer/",
]
crates = []
experts = ["matklad", "petrochenkov"]
familiar = []

[[areas]]
name = "Grammar"
directories = []
crates = []
experts = ["eddyb", "qmx"]
familiar = []

[[areas]]
name = "MIR structure/construction"
directories = [
    "compiler/rustc_middle/mir",
    "compiler/rustc_mir_build/build",
]
crates = []
experts = ["eddyb", "nikomatsakis", "oli-obk"]
familiar = ["davidtwco", "jonas-schievink", "spastorino"]

[[areas]]
name = "MIR optimizations"
directories = [
    "compiler/rustc_mir/transform",
]
crates = []
experts = ["eddyb", "nagisa", "oli-obk"]
familiar = ["jonas-schievink", "spastorino", "tmandry", "wesleywiser"]

[[areas]]
name = "Type layout"
directories = [
    "compiler/rustc_middle/ty/layout.rs",
]
crates = []
experts = ["eddyb", "nagisa", "oli-obk"]
familiar = ["tmandry"]

[[areas]]
name = "match/exhaustiveness"
directories = ["compiler/rustc_mir_build/thir/pattern"]
crates = []
experts = ["nadrieril", "oli-obk"]
familiar = []

[[areas]]
name = "Traits"
directories = ["compiler/rustc_middle/traits", "compiler/rustc_traits"]
crates = []
experts = ["nikomatsakis", "scalexm"]
familiar = []

[[areas]]
name = "Polonius"
directories = []
crates = ["polonius", "datafrog"]
experts = ["nikomatsakis"]
familiar = ["lqd", "spastorino"]

[[areas]]
name = "Libs"
directories = []
crates = []
experts = []
familiar = []

[[areas]]
name = "AST -> HIR lowering"
directories = [
    "compiler/rustc_ast_lowering",
]
crates = []
experts = ["oli-obk"]
familiar = ["davidtwco"]

[[areas]]
name = "debuginfo"
directories = []
crates = []
experts = ["eddyb", "michaelwoerister"]
familiar = ["wesleywiser"]

[[areas]]
name = "drop-check"
directories = []
crates = []
experts = ["pnkfelix"]
familiar = []

[[areas]]
name = "dataflow"
directories = []
crates = []
experts = ["nikomatsakis", "pnkfelix"]
familiar = ["tmandry"]

[[areas]]
name = "AST-borrow checker"
directories = []
crates = []
experts = ["nikomatsakis"]
familiar = []

[[areas]]
name = "MIR borrow check"
directories = []
crates = []
experts = ["matthewjasper", "pnkfelix"]
familiar = ["davidtwco", "spastorino"]

[[areas]]
name = "drop elaboration"
directories = []
crates = []
experts = []
familiar = []

[[areas]]
name = "Privacy"
directories = []
crates = []
experts = ["petrochenkov"]
familiar = ["davidtwco"]

[[areas]]
name = "Name resolution, hygiene"
directories = []
crates = []
experts = ["petrochenkov"]
familiar = []

[[areas]]
name = "Macro expansion"
directories = []
crates = []
experts = ["petrochenkov"]
familiar = []

[[areas]]
name = "`macro_rules` parsing and checking"
directories = [
    "compiler/rustc_expand/mbe.rs"
]
crates = []
experts = ["mark-i-m"]
familiar = []

[[areas]]
name = "Generators"
directories = [
    "library/core/src/ops/generator.rs",
    "compiler/rustc_mir/transform/generator.rs",
    "compiler/rustc_typeck/check/generator_interior.rs",
    "src/test/ui/generator",
]
crates = []
experts = ["tmandry"]
familiar = ["jonas-schievink"]

[[areas]]
name = "Self profiler"
directories = [
    "compiler/rustc_data_structures/profiling.rs",
]
crates = [
    "measureme",
]
experts = ["michaelwoerister", "wesleywiser"]
familiar = []

[[areas]]
name = "Rustdoc"
directories = [
  "src/librustdoc",
  "src/tools/rustdoc",
]
crates = []
experts = ["GuillaumeGomez", "jyn514", "Manishearth", "ollie27"]
familiar = ["kinnison"]

[[areas]]
name = "bootstrap"
directories = [
  "src/bootstrap"
]
crates = []
experts = ["Mark-Simulacrum"]
familiar = ["ehuss", "jyn514"]
